apiVersion: v1
kind: Service

metadata:
  name: my-go-app-service
  namespace: my-app-ns

spec:
  selector:
    app: my-go-app

  ports:
  - port: 80
    targetPort: 8080

  type: NodePort
